version: "3"
services:
  redis-server:
    image: "redis"
    volumes:
      - ${PWD}/redis-data-${ENV}:/var/lib/redis
  node-app:
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      - REDIS_URL=redis://redis-server:6379
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-w", "1", "localhost", "${PORT}"]
      interval: 30s
      timeout: 2s
      retries: 3
